const crypto = require('crypto');
const url = process.env.SUPABASE_URL;
const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
const PEOPLE = ['Richard Darling', 'Anastasia Ferrari', 'Jean-Claude Bērziņš'];
const cents = value => Math.round((Number(value) + Number.EPSILON) * 100) / 100;
const money = value => `€${cents(value).toFixed(2)}`;
const configured = () => Boolean(url && key);
const send = (res, status, value) => res.status(status).json(value);
const headers = extra => ({ apikey: key, Authorization: `Bearer ${key}`, 'Content-Type': 'application/json', ...(extra || {}) });
async function db(path, options = {}) { if (!configured()) throw new Error('Server database settings are not configured yet.'); const response = await fetch(`${url}/rest/v1/${path}`, { ...options, headers: headers(options.headers) }); if (!response.ok) throw new Error(await response.text()); return response.status === 204 ? null : response.json(); }
async function requireManager(actorEmployeeId) {
  if (!actorEmployeeId) throw new Error('Select the manager role before approving or changing a Telegram link.');
  const person = (await db(`employees?id=eq.${encodeURIComponent(actorEmployeeId)}&select=id,name,role`))[0];
  if (!person || person.role !== 'manager') throw new Error('Only the manager account may approve or correct records.');
  return person;
}
function validSplit(s) { const values = ['richard', 'anastasia', 'jeanClaude'].map(k => Number(s?.[k])); if (values.some(v => !Number.isFinite(v) || v < 0 || v > 100) || Math.round(values.reduce((a,b) => a+b, 0)*100) !== 10000) throw new Error('Commission shares must each be 0–100% and total exactly 100%.'); return values; }
function calculateCommissions(amount, percentages) { const pool = cents(Number(amount)*.1), amounts = percentages.map(p => cents(pool*p/100)), diff = cents(pool-amounts.reduce((a,b)=>a+b,0)), i = percentages.findIndex(p=>p===Math.max(...percentages)); amounts[i]=cents(amounts[i]+diff); return { pool, amounts }; }
function b64(v) { return Buffer.from(v).toString('base64url'); }
async function googleToken() { const service = JSON.parse(process.env.GOOGLE_SERVICE_ACCOUNT_JSON || '{}'); if (!service.client_email || !service.private_key) throw new Error('Google Sheets service account is not configured yet.'); const now=Math.floor(Date.now()/1000), input=`${b64(JSON.stringify({alg:'RS256',typ:'JWT'}))}.${b64(JSON.stringify({iss:service.client_email,scope:'https://www.googleapis.com/auth/spreadsheets',aud:'https://oauth2.googleapis.com/token',iat:now,exp:now+3600}))}`, signature=crypto.createSign('RSA-SHA256').update(input).end().sign(service.private_key,'base64url'); const response=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'urn:ietf:params:oauth:grant-type:jwt-bearer',assertion:`${input}.${signature}`})}); if(!response.ok) throw new Error(`Google authorization failed: ${await response.text()}`); return (await response.json()).access_token; }
async function sheetRequest(token, path, options={}) { const response=await fetch(`https://sheets.googleapis.com/v4/spreadsheets/${process.env.GOOGLE_SHEETS_ID}${path}`,{...options,headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json',...(options.headers||{})}}); if(!response.ok) throw new Error(`Google Sheets request failed: ${await response.text()}`); return response.status===204?null:response.json(); }
async function syncSheet(t, splits=[]) { if(!process.env.GOOGLE_SHEETS_ID||!process.env.GOOGLE_SERVICE_ACCOUNT_JSON) throw new Error('Google Sheets settings are not configured yet.'); const token=await googleToken(), book=await sheetRequest(token,''), missing=['Sales','Expenses'].filter(x=>!book.sheets.map(s=>s.properties.title).includes(x)); if(missing.length) await sheetRequest(token,':batchUpdate',{method:'POST',body:JSON.stringify({requests:missing.map(title=>({addSheet:{properties:{title}}}))})}); const sale=t.kind==='sale', tab=sale?'Sales':'Expenses', header=sale?['Reference','Submission time','Salesperson','Customer','Project','Description','Amount EUR','Proposed Richard %','Proposed Anastasia %','Proposed Jean-Claude %','Approved Richard %','Approved Anastasia %','Approved Jean-Claude %','Richard earned EUR','Anastasia earned EUR','Jean-Claude earned EUR','Status']:['Reference','Submission time','Reporter','Description','Category','Amount EUR','Proposed allocation','Final allocation','Status'], ordered=PEOPLE.map(name=>splits.find(s=>s.name===name)||{}), row=sale?[t.reference,t.created_at,t.submitter_name||t.submitter_role,t.customer,t.project,t.description,Number(t.amount),...ordered.map(s=>s.proposed_percent??''),...ordered.map(s=>s.final_percent??''),...ordered.map(s=>s.earned_amount??0),t.status]:[t.reference,t.created_at,t.submitter_name||t.submitter_role,t.description,t.expense_category,Number(t.amount),t.proposed_allocation,t.final_allocation||'',t.status]; const values=await sheetRequest(token,`/values/${encodeURIComponent(`${tab}!A:Q`)}`), rows=values.values||[]; if(!rows.length) await sheetRequest(token,`/values/${encodeURIComponent(`${tab}!A1:Q1`)}?valueInputOption=USER_ENTERED`,{method:'PUT',body:JSON.stringify({values:[header]})}); const ix=rows.findIndex(r=>r[0]===t.reference); if(ix>=0) await sheetRequest(token,`/values/${encodeURIComponent(`${tab}!A${ix+1}:Q${ix+1}`)}?valueInputOption=USER_ENTERED`,{method:'PUT',body:JSON.stringify({values:[row]})}); else await sheetRequest(token,`/values/${encodeURIComponent(`${tab}!A:Q`)}:append?valueInputOption=USER_ENTERED&insertDataOption=INSERT_ROWS`,{method:'POST',body:JSON.stringify({values:[row]})}); await db(`transactions?id=eq.${t.id}`,{method:'PATCH',body:JSON.stringify({sheet_sync_status:'synced',sheet_sync_error:null})}); }
async function attemptSheetSync(t,s) { try { await syncSheet(t,s); return {status:'synced'}; } catch(error) { await db(`transactions?id=eq.${t.id}`,{method:'PATCH',body:JSON.stringify({sheet_sync_status:'failed',sheet_sync_error:error.message})}); return {status:'failed',error:error.message}; } }
async function notify(t,text) { if(!t.originating_chat_id) return {status:'not_applicable',error:'No Telegram recipient linked'}; const token=process.env.TELEGRAM_BOT_TOKEN; if(!token) return {status:'failed',error:'Telegram bot is not configured yet.'}; try { const response=await fetch(`https://api.telegram.org/bot${token}/sendMessage`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({chat_id:t.originating_chat_id,text})}); if(!response.ok) throw new Error(await response.text()); await db(`transactions?id=eq.${t.id}`,{method:'PATCH',body:JSON.stringify({notification_status:'sent',notification_error:null})}); return {status:'sent'}; } catch(error) { await db(`transactions?id=eq.${t.id}`,{method:'PATCH',body:JSON.stringify({notification_status:'failed',notification_error:error.message})}); return {status:'failed',error:error.message}; } }
module.exports={PEOPLE,db,send,cents,money,configured,requireManager,validSplit,calculateCommissions,attemptSheetSync,notify};
